language: cpp
os: linux
dist: trusty
sudo: required

before_install: 
  - sudo apt install cmake g++ pkg-config libssl-dev libprocps-dev libboost-all-dev libgmp-dev
  - ./get-libsnark

script:
  - make
  - ./test
